### ISSUE TITLE
gin框架只能生成url，没有请求body

### ISSUE THREAD

**Issue by ZHOUXING1997** [zhangjianay/quick-request#6]

**Comment by zhangjianay** [comment]
你先提供下你的请求的截图，等后面有时间可以看下怎么生成

**Comment by zhangjianay** [comment]
后面再看能否提供，不过你可以先试着编辑一次参数，保存后，后续可以直接调出使用

**Comment by ZHOUXING1997** [comment]
Ok，这个不是必须的。
手动也行，本来url也得改域名




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangjianay/quick-request"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangjianay/quick-request] gin框架只能生成url，没有请求body (Issue #6)





 
后面再看能否提供，不过你可以先试着编辑一次参数，保存后，后续可以直接调出使用

**Comment by zhangjianay** [comment]
看在最新版本，已经支持你这种方式，有问题再沟通

**Comment by ZHOUXING1997** [comment]
ok,ok，辛苦。
有时间体验一下




周星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangjianay/quick-request"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月13日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangjianay/quick-request] gin框架只能生成url，没有请求body (Issue #6)





 
看在最新版本，已经支持你这种方式，有问题再沟通
